#!/bin/sh

case "${XDG_CURRENT_DESKTOP}" in
KDE|KDE-*)
	TOOL=qarma
	;;
*)
	TOOL=zenity-gtk
	;;
esac

if ! command -v "$TOOL" >/dev/null 2>&1; then
	if command -v zenity-gtk >/dev/null 2>&1; then
		TOOL=zenity-gtk
	else
		echo "Neither zenity nor qarma is installed." >&2
		exit 1
	fi
fi

exec "$TOOL" "$@"
